name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        meteor: [1.12.2, 2.6.1]
        redis-version: [4, 5, 6]

    steps:
      - uses: actions/checkout@v3

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Setup Meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ matrix.meteor }}
      - run: meteor create --release 1.12.2 --bare test
      - run: cd test
      - run: meteor npm i --save puppeteer@1.18.1 simpl-schema chai
      - run: METEOR_PACKAGE_DIRS="$GITHUB_WORKSPACE" TEST_BROWSER_DRIVER=puppeteer meteor test-packages --raw-logs --once --driver-package meteortesting:mocha $GITHUB_WORKSPACE
